spring:
  kafka:
    consumer:
      group-id: industry-service-group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer